name: ✨ 功能建议 / Feature Request
description: 提出新功能或改进建议 / Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！我们非常重视用户的反馈。
        
        Thanks for your suggestion! We value user feedback.

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型 / Feature Type
      description: 这是什么类型的功能？
      options:
        - 新平台支持 / New platform support
        - 现有功能改进 / Existing feature improvement
        - 用户界面优化 / UI/UX improvement
        - AI 生成优化 / AI generation improvement
        - 新功能 / New feature
        - 其他 / Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述 / Feature Description
      description: 请详细描述您希望添加的功能
      placeholder: |
        我希望能够支持发布到小红书平台...
        
        I would like to be able to publish to Xiaohongshu...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景 / Use Case
      description: 这个功能会在什么场景下使用？解决什么问题？
      placeholder: |
        作为一个自媒体运营者，我需要同时在多个平台发布内容，小红书是我的主要平台之一...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 建议方案 / Proposed Solution
      description: 如果您有具体的实现想法，请描述
      placeholder: |
        可以参考头条的实现方式，添加小红书的 Cookie 配置和内容脚本...

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternatives Considered
      description: 您是否考虑过其他替代方案？
      placeholder: |
        目前我只能手动复制粘贴内容到小红书...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级 / Priority
      description: 您认为这个功能的重要程度
      options:
        - 高 - 严重影响使用 / High - Significantly impacts usage
        - 中 - 有帮助但不紧急 / Medium - Helpful but not urgent
        - 低 - 锦上添花 / Low - Nice to have

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿 / Contribution
      description: 您是否愿意参与这个功能的开发？
      options:
        - label: 我愿意提交 PR 来实现这个功能 / I'm willing to submit a PR for this feature
        - label: 我可以帮忙测试 / I can help with testing
        - label: 我可以提供更多信息 / I can provide more information

  - type: textarea
    id: additional
    attributes:
      label: 补充信息 / Additional Context
      description: 其他任何相关信息、截图或参考链接
